### ISSUE TITLE
Compare performance of implementations

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/Probabilistic-Peridynamics#59]
Compare performance of current OpenCL implementation vs. Ben's implementation for a wide range of problem sizes/dimensions/parameters.

**Comment by bb515** [comment]
Result is
model_cl_ben (Ben's opencl) is 3 to 10x (on average. 7) times quicker than model_cl (Jim's OpenCL) , and 80x quicker than model (cython)
