### ISSUE TITLE
Extend extra features of ModelCLBen to Model?

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/Probabilistic-Peridynamics#69]
Talk to Tim about this

**Comment by bb515** [comment]
We decided against extending all of the extra features (such as n-material types, n-linear damage model), however, I have, in mind of uniformity between implementations, extended the following extra features of ModelCLBen to Model:
- General force boundary conditions
- General displacement boundary conditions
- Ability to measure the displacements/ force on a "tip", a specified geometric region of interest.
